name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - master
      - TestBranch
  workflow_dispatch:

env:
  IMAGE_NAME: ssprajapati2021/myauthapi
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          containerAppName: CONTAINER_APP_NAME: ${{ github.ref_name == 'master' && 'my-auth-container-app' || 'my-auth-test-app' }}
          resourceGroup: rg-container
